---
name: nim test

on:
  push:
    branches:
      - main
    paths-ignore:
      - README*
      - LICENSE
      - '**.md'
  pull_request:
    paths-ignore:
      - README*
      - LICENSE
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
        nim:
          - '1.4.0'
          - '1.4.x'
          - '1.6.0'
          - '1.6.x'
          - 'stable'
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: nimble install -Y
      - run: nimble test -Y
